//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sumerics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sumerics.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current position is {0}° {1}° with heading {2}° north..
        /// </summary>
        public static string AboutPositionMessage {
            get {
                return ResourceManager.GetString("AboutPositionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        public static string Accelerometer {
            get {
                return ResourceManager.GetString("Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer:.
        /// </summary>
        public static string AccelerometerLabel {
            get {
                return ResourceManager.GetString("AccelerometerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string AutomaticHint {
            get {
                return ResourceManager.GetString("AutomaticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to the topic.
        /// </summary>
        public static string BackToolTip {
            get {
                return ResourceManager.GetString("BackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change working directory.
        /// </summary>
        public static string ChangeWorkingDirectory {
            get {
                return ResourceManager.GetString("ChangeWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color palette:.
        /// </summary>
        public static string ColorPaletteLabel {
            get {
                return ResourceManager.GetString("ColorPaletteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to show:.
        /// </summary>
        public static string ColumnsLabel {
            get {
                return ResourceManager.GetString("ColumnsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command history:.
        /// </summary>
        public static string CommandHistoryLabel {
            get {
                return ResourceManager.GetString("CommandHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass:.
        /// </summary>
        public static string CompassLabel {
            get {
                return ResourceManager.GetString("CompassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour settings.
        /// </summary>
        public static string ContourSettings {
            get {
                return ResourceManager.GetString("ContourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( copy ).
        /// </summary>
        public static string CopyCommand {
            get {
                return ResourceManager.GetString("CopyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize current subplot.
        /// </summary>
        public static string CustomizeSubplot {
            get {
                return ResourceManager.GetString("CustomizeSubplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title here.
        /// </summary>
        public static string DataTitleHint {
            get {
                return ResourceManager.GetString("DataTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data title:.
        /// </summary>
        public static string DataTitleLabel {
            get {
                return ResourceManager.GetString("DataTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision required.
        /// </summary>
        public static string DecisionRequired {
            get {
                return ResourceManager.GetString("DecisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw input.
        /// </summary>
        public static string DrawInputToolTip {
            get {
                return ResourceManager.GetString("DrawInputToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel closing..
        /// </summary>
        public static string EditorSaveAnswerCancel {
            get {
                return ResourceManager.GetString("EditorSaveAnswerCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, but thanks!.
        /// </summary>
        public static string EditorSaveAnswerNo {
            get {
                return ResourceManager.GetString("EditorSaveAnswerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, save the changes..
        /// </summary>
        public static string EditorSaveAnswerYes {
            get {
                return ResourceManager.GetString("EditorSaveAnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I want to save them..
        /// </summary>
        public static string EditorSaveAnswerYesMultiple {
            get {
                return ResourceManager.GetString("EditorSaveAnswerYesMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content has been changed. Save the changes?.
        /// </summary>
        public static string EditorSaveQuestion {
            get {
                return ResourceManager.GetString("EditorSaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} unsaved file(s). Do you want to save them?.
        /// </summary>
        public static string EditorSaveQuestionMultiple {
            get {
                return ResourceManager.GetString("EditorSaveQuestionMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        public static string EditorUntitledFile {
            get {
                return ResourceManager.GetString("EditorUntitledFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter quick statement.
        /// </summary>
        public static string EnterQuickStatement {
            get {
                return ResourceManager.GetString("EnterQuickStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file.
        /// </summary>
        public static string ErrorCannotOpenFile {
            get {
                return ResourceManager.GetString("ErrorCannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save file.
        /// </summary>
        public static string ErrorCannotSaveFile {
            get {
                return ResourceManager.GetString("ErrorCannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log:.
        /// </summary>
        public static string ErrorLogLabel {
            get {
                return ResourceManager.GetString("ErrorLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating {0}.
        /// </summary>
        public static string EvaluateFile {
            get {
                return ResourceManager.GetString("EvaluateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate input.
        /// </summary>
        public static string EvaluateInput {
            get {
                return ResourceManager.GetString("EvaluateInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate math drawings:.
        /// </summary>
        public static string EvaluateMathDrawingsLabel {
            get {
                return ResourceManager.GetString("EvaluateMathDrawingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File created.
        /// </summary>
        public static string FileCreated {
            get {
                return ResourceManager.GetString("FileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global startup script:
        ///(requires admin privileges).
        /// </summary>
        public static string GlobalStartupScriptLabel {
            get {
                return ResourceManager.GetString("GlobalStartupScriptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyrometer.
        /// </summary>
        public static string Gyrometer {
            get {
                return ResourceManager.GetString("Gyrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyrometer:.
        /// </summary>
        public static string GyrometerLabel {
            get {
                return ResourceManager.GetString("GyrometerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatmap settings.
        /// </summary>
        public static string HeatmapSettings {
            get {
                return ResourceManager.GetString("HeatmapSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (px).
        /// </summary>
        public static string HeightInPx {
            get {
                return ResourceManager.GetString("HeightInPx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinometer.
        /// </summary>
        public static string Inclinometer {
            get {
                return ResourceManager.GetString("Inclinometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinometer:.
        /// </summary>
        public static string InclinometerLabel {
            get {
                return ResourceManager.GetString("InclinometerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        public static string InfoToolTip {
            get {
                return ResourceManager.GetString("InfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your input here..
        /// </summary>
        public static string InputHint {
            get {
                return ResourceManager.GetString("InputHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Required.
        /// </summary>
        public static string InputRequired {
            get {
                return ResourceManager.GetString("InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} keyword..
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend background color:.
        /// </summary>
        public static string LegendBackgroundColorLabel {
            get {
                return ResourceManager.GetString("LegendBackgroundColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend border color:.
        /// </summary>
        public static string LegendBorderColorLabel {
            get {
                return ResourceManager.GetString("LegendBorderColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend position:.
        /// </summary>
        public static string LegendPositionLabel {
            get {
                return ResourceManager.GetString("LegendPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light:.
        /// </summary>
        public static string LightLabel {
            get {
                return ResourceManager.GetString("LightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livestream:.
        /// </summary>
        public static string LivestreamLabel {
            get {
                return ResourceManager.GetString("LivestreamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load workspace.
        /// </summary>
        public static string LoadWorkspace {
            get {
                return ResourceManager.GetString("LoadWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable {0}..
        /// </summary>
        public static string LocalVariable {
            get {
                return ResourceManager.GetString("LocalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum entries:.
        /// </summary>
        public static string MaximumEntriesLabel {
            get {
                return ResourceManager.GetString("MaximumEntriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More help topics.
        /// </summary>
        public static string MoreToolTip {
            get {
                return ResourceManager.GetString("MoreToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string NewFileToolTip {
            get {
                return ResourceManager.GetString("NewFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description available..
        /// </summary>
        public static string NoDescriptionAvailable {
            get {
                return ResourceManager.GetString("NoDescriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No examples available..
        /// </summary>
        public static string NoExamplesAvailable {
            get {
                return ResourceManager.GetString("NoExamplesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usages available..
        /// </summary>
        public static string NoUsagesAvailable {
            get {
                return ResourceManager.GetString("NoUsagesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open documentation.
        /// </summary>
        public static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open editor.
        /// </summary>
        public static string OpenEditor {
            get {
                return ResourceManager.GetString("OpenEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file....
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string OpenFileToolTip {
            get {
                return ResourceManager.GetString("OpenFileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am not sure, please cancel..
        /// </summary>
        public static string OverwriteAnswerCancel {
            get {
                return ResourceManager.GetString("OverwriteAnswerCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure, go ahead and overwrite it..
        /// </summary>
        public static string OverwriteAnswerYes {
            get {
                return ResourceManager.GetString("OverwriteAnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the file {0}?.
        /// </summary>
        public static string OverwriteQuestion {
            get {
                return ResourceManager.GetString("OverwriteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places.
        /// </summary>
        public static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the statement here..
        /// </summary>
        public static string PlaceTheStatement {
            get {
                return ResourceManager.GetString("PlaceTheStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plot has been successfully saved in the file {0}..
        /// </summary>
        public static string PlotSavedMessage {
            get {
                return ResourceManager.GetString("PlotSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot settings.
        /// </summary>
        public static string PlotSettings {
            get {
                return ResourceManager.GetString("PlotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title here.
        /// </summary>
        public static string PlotTitleHint {
            get {
                return ResourceManager.GetString("PlotTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the plot:.
        /// </summary>
        public static string PlotTitleLabel {
            get {
                return ResourceManager.GetString("PlotTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins can extend the possibilities of Sumerics. Including a plugin is quite straight forward. Just place the plugin you want to include in the subfolder plugins of Sumerics. It will then be shown in the list below. This list is the location where you can enable or disable existing plugins..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG File.
        /// </summary>
        public static string PngFile {
            get {
                return ResourceManager.GetString("PngFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickview.
        /// </summary>
        public static string Quickview {
            get {
                return ResourceManager.GetString("Quickview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes require a restart of the application..
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns.
        /// </summary>
        public static string Returns {
            get {
                return ResourceManager.GetString("Returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows to show:.
        /// </summary>
        public static string RowsLabel {
            get {
                return ResourceManager.GetString("RowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrations and samples.
        /// </summary>
        public static string SamplesDescription {
            get {
                return ResourceManager.GetString("SamplesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file....
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image....
        /// </summary>
        public static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save plot as ....
        /// </summary>
        public static string SavePlotAs {
            get {
                return ResourceManager.GetString("SavePlotAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save workspace.
        /// </summary>
        public static string SaveWorkspace {
            get {
                return ResourceManager.GetString("SaveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search help.
        /// </summary>
        public static string SearchHelp {
            get {
                return ResourceManager.GetString("SearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search variables.
        /// </summary>
        public static string SearchVariables {
            get {
                return ResourceManager.GetString("SearchVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor plots.
        /// </summary>
        public static string SensorPlots {
            get {
                return ResourceManager.GetString("SensorPlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series settings.
        /// </summary>
        public static string SeriesSettings {
            get {
                return ResourceManager.GetString("SeriesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title here.
        /// </summary>
        public static string SeriesTitleHint {
            get {
                return ResourceManager.GetString("SeriesTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series title:.
        /// </summary>
        public static string SeriesTitleLabel {
            get {
                return ResourceManager.GetString("SeriesTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend visible.
        /// </summary>
        public static string ShowLegendHint {
            get {
                return ResourceManager.GetString("ShowLegendHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the legend:.
        /// </summary>
        public static string ShowLegendLabel {
            get {
                return ResourceManager.GetString("ShowLegendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines visible.
        /// </summary>
        public static string ShowLevelsHint {
            get {
                return ResourceManager.GetString("ShowLevelsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show levels:.
        /// </summary>
        public static string ShowLevelsLabel {
            get {
                return ResourceManager.GetString("ShowLevelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lines:.
        /// </summary>
        public static string ShowLinesLabel {
            get {
                return ResourceManager.GetString("ShowLinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subplot settings.
        /// </summary>
        public static string SubplotSettings {
            get {
                return ResourceManager.GetString("SubplotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol:.
        /// </summary>
        public static string SymbolLabel {
            get {
                return ResourceManager.GetString("SymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textfile.
        /// </summary>
        public static string Textfile {
            get {
                return ResourceManager.GetString("Textfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title here.
        /// </summary>
        public static string TitleHint {
            get {
                return ResourceManager.GetString("TitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the plot:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Numerics uses the following packages:.
        /// </summary>
        public static string UsedPackages {
            get {
                return ResourceManager.GetString("UsedPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User startup script:.
        /// </summary>
        public static string UserStartupScriptLabel {
            get {
                return ResourceManager.GetString("UserStartupScriptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        public static string Variable {
            get {
                return ResourceManager.GetString("Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in editor.
        /// </summary>
        public static string ViewInEditor {
            get {
                return ResourceManager.GetString("ViewInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        public static string Visualization {
            get {
                return ResourceManager.GetString("Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch samples.
        /// </summary>
        public static string WatchSamples {
            get {
                return ResourceManager.GetString("WatchSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (px).
        /// </summary>
        public static string WidthInPx {
            get {
                return ResourceManager.GetString("WidthInPx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAMP Script.
        /// </summary>
        public static string YampScript {
            get {
                return ResourceManager.GetString("YampScript", resourceCulture);
            }
        }
    }
}
