//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sumerics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sumerics.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current position is {0}° {1}° with heading {2}° north..
        /// </summary>
        public static string AboutPositionMessage {
            get {
                return ResourceManager.GetString("AboutPositionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        public static string Accelerometer {
            get {
                return ResourceManager.GetString("Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer:.
        /// </summary>
        public static string AccelerometerLabel {
            get {
                return ResourceManager.GetString("AccelerometerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string AutomaticHint {
            get {
                return ResourceManager.GetString("AutomaticHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change working directory.
        /// </summary>
        public static string ChangeWorkingDirectory {
            get {
                return ResourceManager.GetString("ChangeWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color palette:.
        /// </summary>
        public static string ColorPaletteLabel {
            get {
                return ResourceManager.GetString("ColorPaletteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to show:.
        /// </summary>
        public static string ColumnsLabel {
            get {
                return ResourceManager.GetString("ColumnsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command history:.
        /// </summary>
        public static string CommandHistoryLabel {
            get {
                return ResourceManager.GetString("CommandHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        public static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass:.
        /// </summary>
        public static string CompassLabel {
            get {
                return ResourceManager.GetString("CompassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour settings.
        /// </summary>
        public static string ContourSettings {
            get {
                return ResourceManager.GetString("ContourSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize current subplot.
        /// </summary>
        public static string CustomizeSubplot {
            get {
                return ResourceManager.GetString("CustomizeSubplot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title here.
        /// </summary>
        public static string DataTitleHint {
            get {
                return ResourceManager.GetString("DataTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data title:.
        /// </summary>
        public static string DataTitleLabel {
            get {
                return ResourceManager.GetString("DataTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision required.
        /// </summary>
        public static string DecisionRequired {
            get {
                return ResourceManager.GetString("DecisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter quick statement.
        /// </summary>
        public static string EnterQuickStatement {
            get {
                return ResourceManager.GetString("EnterQuickStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error log:.
        /// </summary>
        public static string ErrorLogLabel {
            get {
                return ResourceManager.GetString("ErrorLogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate input.
        /// </summary>
        public static string EvaluateInput {
            get {
                return ResourceManager.GetString("EvaluateInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate math drawings:.
        /// </summary>
        public static string EvaluateMathDrawingsLabel {
            get {
                return ResourceManager.GetString("EvaluateMathDrawingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global startup script:
        ///(requires admin privileges).
        /// </summary>
        public static string GlobalStartupScriptLabel {
            get {
                return ResourceManager.GetString("GlobalStartupScriptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyrometer.
        /// </summary>
        public static string Gyrometer {
            get {
                return ResourceManager.GetString("Gyrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyrometer:.
        /// </summary>
        public static string GyrometerLabel {
            get {
                return ResourceManager.GetString("GyrometerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (px).
        /// </summary>
        public static string HeightInPx {
            get {
                return ResourceManager.GetString("HeightInPx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinometer.
        /// </summary>
        public static string Inclinometer {
            get {
                return ResourceManager.GetString("Inclinometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclinometer:.
        /// </summary>
        public static string InclinometerLabel {
            get {
                return ResourceManager.GetString("InclinometerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string Interaction {
            get {
                return ResourceManager.GetString("Interaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend background color:.
        /// </summary>
        public static string LegendBackgroundColorLabel {
            get {
                return ResourceManager.GetString("LegendBackgroundColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend border color:.
        /// </summary>
        public static string LegendBorderColorLabel {
            get {
                return ResourceManager.GetString("LegendBorderColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend position:.
        /// </summary>
        public static string LegendPositionLabel {
            get {
                return ResourceManager.GetString("LegendPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light:.
        /// </summary>
        public static string LightLabel {
            get {
                return ResourceManager.GetString("LightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Livestream:.
        /// </summary>
        public static string LivestreamLabel {
            get {
                return ResourceManager.GetString("LivestreamLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load workspace.
        /// </summary>
        public static string LoadWorkspace {
            get {
                return ResourceManager.GetString("LoadWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum entries:.
        /// </summary>
        public static string MaximumEntriesLabel {
            get {
                return ResourceManager.GetString("MaximumEntriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open documentation.
        /// </summary>
        public static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open editor.
        /// </summary>
        public static string OpenEditor {
            get {
                return ResourceManager.GetString("OpenEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file....
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place the statement here..
        /// </summary>
        public static string PlaceTheStatement {
            get {
                return ResourceManager.GetString("PlaceTheStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot settings.
        /// </summary>
        public static string PlotSettings {
            get {
                return ResourceManager.GetString("PlotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title here.
        /// </summary>
        public static string PlotTitleHint {
            get {
                return ResourceManager.GetString("PlotTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the plot:.
        /// </summary>
        public static string PlotTitleLabel {
            get {
                return ResourceManager.GetString("PlotTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins can extend the possibilities of Sumerics. Including a plugin is quite straight forward. Just place the plugin you want to include in the subfolder plugins of Sumerics. It will then be shown in the list below. This list is the location where you can enable or disable existing plugins..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        public static string Plugins {
            get {
                return ResourceManager.GetString("Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickview.
        /// </summary>
        public static string Quickview {
            get {
                return ResourceManager.GetString("Quickview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes require a restart of the application..
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows to show:.
        /// </summary>
        public static string RowsLabel {
            get {
                return ResourceManager.GetString("RowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Samples {
            get {
                return ResourceManager.GetString("Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrations and samples.
        /// </summary>
        public static string SamplesDescription {
            get {
                return ResourceManager.GetString("SamplesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file....
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image....
        /// </summary>
        public static string SaveImage {
            get {
                return ResourceManager.GetString("SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save workspace.
        /// </summary>
        public static string SaveWorkspace {
            get {
                return ResourceManager.GetString("SaveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search help.
        /// </summary>
        public static string SearchHelp {
            get {
                return ResourceManager.GetString("SearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search variables.
        /// </summary>
        public static string SearchVariables {
            get {
                return ResourceManager.GetString("SearchVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor plots.
        /// </summary>
        public static string SensorPlots {
            get {
                return ResourceManager.GetString("SensorPlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series settings.
        /// </summary>
        public static string SeriesSettings {
            get {
                return ResourceManager.GetString("SeriesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title here.
        /// </summary>
        public static string SeriesTitleHint {
            get {
                return ResourceManager.GetString("SeriesTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series title:.
        /// </summary>
        public static string SeriesTitleLabel {
            get {
                return ResourceManager.GetString("SeriesTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend visible.
        /// </summary>
        public static string ShowLegendHint {
            get {
                return ResourceManager.GetString("ShowLegendHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the legend:.
        /// </summary>
        public static string ShowLegendLabel {
            get {
                return ResourceManager.GetString("ShowLegendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines visible.
        /// </summary>
        public static string ShowLevelsHint {
            get {
                return ResourceManager.GetString("ShowLevelsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show levels:.
        /// </summary>
        public static string ShowLevelsLabel {
            get {
                return ResourceManager.GetString("ShowLevelsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show lines:.
        /// </summary>
        public static string ShowLinesLabel {
            get {
                return ResourceManager.GetString("ShowLinesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subplot settings.
        /// </summary>
        public static string SubplotSettings {
            get {
                return ResourceManager.GetString("SubplotSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol:.
        /// </summary>
        public static string SymbolLabel {
            get {
                return ResourceManager.GetString("SymbolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the title here.
        /// </summary>
        public static string TitleHint {
            get {
                return ResourceManager.GetString("TitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the plot:.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Numerics uses the following packages:.
        /// </summary>
        public static string UsedPackages {
            get {
                return ResourceManager.GetString("UsedPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User startup script:.
        /// </summary>
        public static string UserStartupScriptLabel {
            get {
                return ResourceManager.GetString("UserStartupScriptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in editor.
        /// </summary>
        public static string ViewInEditor {
            get {
                return ResourceManager.GetString("ViewInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        public static string Visualization {
            get {
                return ResourceManager.GetString("Visualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch samples.
        /// </summary>
        public static string WatchSamples {
            get {
                return ResourceManager.GetString("WatchSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (px).
        /// </summary>
        public static string WidthInPx {
            get {
                return ResourceManager.GetString("WidthInPx", resourceCulture);
            }
        }
    }
}
